// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY8l_ms-QAyhnSmubNQvTlYZpThYJCszU',
    appId: '1:1050949341775:web:012d60be6482bf3c33903a',
    messagingSenderId: '1050949341775',
    projectId: 'progress-tracker-150106',
    authDomain: 'progress-tracker-150106.firebaseapp.com',
    storageBucket: 'progress-tracker-150106.firebasestorage.app',
    measurementId: 'G-ZN2SHYRPQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApOQZu_cZQVs8Lvpv4QmMclrRW1-jZ9RE',
    appId: '1:1050949341775:android:8ad56816b619586c33903a',
    messagingSenderId: '1050949341775',
    projectId: 'progress-tracker-150106',
    storageBucket: 'progress-tracker-150106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfPf6Hgbn0W0WgsY8iVNnm6LOuh6Mvv1E',
    appId: '1:1050949341775:ios:e8bc26ed145030ed33903a',
    messagingSenderId: '1050949341775',
    projectId: 'progress-tracker-150106',
    storageBucket: 'progress-tracker-150106.firebasestorage.app',
    iosBundleId: 'com.example.progressTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfPf6Hgbn0W0WgsY8iVNnm6LOuh6Mvv1E',
    appId: '1:1050949341775:ios:e8bc26ed145030ed33903a',
    messagingSenderId: '1050949341775',
    projectId: 'progress-tracker-150106',
    storageBucket: 'progress-tracker-150106.firebasestorage.app',
    iosBundleId: 'com.example.progressTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY8l_ms-QAyhnSmubNQvTlYZpThYJCszU',
    appId: '1:1050949341775:web:69cff00d3a2b53f233903a',
    messagingSenderId: '1050949341775',
    projectId: 'progress-tracker-150106',
    authDomain: 'progress-tracker-150106.firebaseapp.com',
    storageBucket: 'progress-tracker-150106.firebasestorage.app',
    measurementId: 'G-J4HMP60J54',
  );
}
